# espanso configuration file

# Thip is the default configuration file, change it as you like it
# Yopanso status
# can refer to the official documentation:
# https://espanso.org/docs/
search_shortcut: off
search_trigger: off
toggle_key: RIGHT_CTRL
