# exports
export VISUAL=vim
export EDITOR=vim
export TERMINAL=urxvt
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# setup path
PATH=$PATH:$(ruby -e 'print Gem.user_dir')/bin:$HOME/.node_modules/bin:$HOME/bin
FPATH=$FPATH:$HOME/.fpath
