#####################
# SETUP ENVIRONMENT #
#####################

# Path
# Add binaries from dotfiles
PATH=$HOME/.bin:$HOME/.local/bin:$PATH
# Use local node modules binaries before global binaries
PATH=./node_modules/.bin:$PATH

# Defaults
if (( $+commands[st] )); then
  export TERMINAL=st
else
  export TERMINAL=urxvt
fi

if (( $+commands[docker] )); then
  export VISUAL=nvim
  export EDITOR=nvim
else
  export VISUAL=vim
  export EDITOR=vim
fi

if [ -n "$DISPLAY" ]; then
  export BROWSER=firefox
else
  export BROWSER=w3m
fi

# set qt5 to use adwaita
# ref: https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#Styles_for_both_Qt_and_GTK+
QT_STYLE_OVERRIDE=adwaita

# prevent Firefox from creating Desktop directory
export XDG_DESKTOP_DIR="$HOME/Downloads"

# GnuPG
# Set to current
export GPG_TTY=$(tty)
# Refresh gpg-agent tty in case user switches into an X session
gpg-connect-agent updatestartuptty /bye >/dev/null

# Solarized Dircolors
# see: https://github.com/seebi/dircolors-solarized
eval `dircolors $HOME/dotfiles/zsh/dir_colors`

# node version manager
# lazy loading saves on shell startup time
if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
  nvm() {
    unset -f nvm;
    export NVM_DIR="$HOME/.nvm"
    source "$NVM_DIR/nvm.sh"
    nvim "$@"
  }
fi

# Init FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Disable LiquidPrompt temperature sensor calls on linode machine
# Do this before initializing Zimfw
if [ "$HOSTNAME" = linode ]; then
  LP_ENABLE_TEMP=0
fi

# Zimfw
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi

_gen_fzf_default_opts() {
  export FZF_DEFAULT_OPTS="
    --color=bg+:7,bg:15,spinner:6,hl:4
    --color=fg:11,header:4,info:3,pointer:6
    --color=marker:6,fg+:0,prompt:3,hl+:4
  "
}

_gen_fzf_default_opts
