#####################
# SETUP ENVIRONMENT #
#####################

# Add binaries from dotfiles
PATH=$HOME/.bin:$HOME/.local/bin:$PATH

export TERMINAL=st

if (( $+commands[docker] )); then
  export VISUAL=nvim
  export EDITOR=nvim
else
  export VISUAL=vim
  export EDITOR=vim
fi

# use gui browser if running x11/wayland
if [ -n "$DISPLAY" ]; then
  export BROWSER=firefox
else
  export BROWSER=w3m
fi

# Solarized Dircolors
# see: https://github.com/seebi/dircolors-solarized
eval `dircolors $HOME/dotfiles/zsh/dir_colors`

# set qt5 to use adwaita
# ref: https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#Styles_for_both_Qt_and_GTK+
QT_STYLE_OVERRIDE=adwaita

# prevent Firefox from creating Desktop directory
export XDG_DESKTOP_DIR="$HOME/Downloads"

# GnuPG
# Set to current
export GPG_TTY=$(tty)
# Refresh gpg-agent tty in case user switches into an X session
gpg-connect-agent updatestartuptty /bye >/dev/null

# Use local node modules binaries before global binaries
PATH=./node_modules/.bin:$PATH

# node version manager
export NVM_DIR="${XDG_CONFIG_HOME/:-$HOME/.}nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Init FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# FZF style
_gen_fzf_default_opts() {
  export FZF_DEFAULT_OPTS="
    --color=bg+:7,bg:15,spinner:6,hl:4
    --color=fg:11,header:4,info:3,pointer:6
    --color=marker:6,fg+:0,prompt:3,hl+:4
  "
}
_gen_fzf_default_opts

# Disable LiquidPrompt temperature sensor calls on linode machine
# Do this before initializing Zimfw
if [ "$HOSTNAME" = linode ]; then
  LP_ENABLE_TEMP=0
fi

# Zimfw
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi
